
const questions = [
  { q: "Hewan apa yang bisa hidup di dua alam?", a: "katak" },
  { q: "Hewan apa yang bisa terbang di malam hari dan suka buah?", a: "kalong" },
  { q: "Hewan yang suka mengeong?", a: "kucing" },
  { q: "Hewan berkaki delapan yang membuat jaring?", a: "laba-laba" },
  { q: "Hewan apa yang pandai meniru ucapan manusia?", a: "burung beo" },
  { q: "Hewan yang paling besar di laut?", a: "paus" },
  { q: "Hewan apa yang suka meloncat dan hidup di Australia?", a: "kanguru" },
  { q: "Hewan apa yang bisa menyemburkan tinta?", a: "cumi-cumi" },
  { q: "Hewan yang paling lambat di dunia?", a: "siput" },
  { q: "Hewan apa yang kulitnya belang hitam putih?", a: "zebra" },
  { q: "Hewan apa yang bertaring dan suka madu?", a: "beruang" },
  { q: "Hewan apa yang punya belalai panjang?", a: "gajah" },
  { q: "Hewan kecil yang suka terbang di malam hari dan menghisap darah?", a: "nyamuk" },
  { q: "Hewan berleher panjang dari Afrika?", a: "jerapah" },
  { q: "Hewan laut yang punya capit besar?", a: "kepiting" },
  { q: "Hewan yang melilit mangsanya?", a: "ular" },
  { q: "Hewan yang punya tanduk dan suka menyeruduk?", a: "banteng" },
  { q: "Hewan apa yang sering dijadikan peliharaan dan bisa menggonggong?", a: "anjing" },
  { q: "Hewan apa yang bisa berjalan di dinding?", a: "cicak" },
  { q: "Hewan apa yang hidup di kutub dan berwarna putih?", a: "beruang kutub" },
  { q: "Hewan apa yang berbisa dan menjulurkan lidah?", a: "ular" },
  { q: "Hewan apa yang suka melompat dan hidup di sawah?", a: "kodok" },
  { q: "Hewan yang suka makan wortel dan punya telinga panjang?", a: "kelinci" },
  { q: "Hewan berkaki dua yang bertelur dan bisa berkokok?", a: "ayam" },
  { q: "Hewan penghasil susu dan makan rumput?", a: "sapi" },
  { q: "Hewan yang berduri dan bisa menggulung diri?", a: "landak" },
  { q: "Hewan yang bentuknya pipih dan menempel di tubuh?", a: "lintah" },
  { q: "Hewan laut yang bisa berubah warna?", a: "gurita" },
  { q: "Hewan yang punya cangkang dan berjalan lambat?", a: "keong" },
  { q: "Hewan yang punya surai dan disebut raja hutan?", a: "singa" },
  { q: "Hewan kecil bersayap yang suka bunga?", a: "kupu-kupu" },
  { q: "Hewan malam yang bisa berputar kepalanya hampir 360 derajat?", a: "burung hantu" },
  { q: "Hewan besar bercula satu yang hampir punah?", a: "badak" },
  { q: "Hewan yang suka menyelam dan tidak bisa terbang?", a: "penguin" },
  { q: "Hewan laut berbentuk bintang?", a: "bintang laut" },
  { q: "Hewan penghasil telur asin?", a: "bebek" },
  { q: "Hewan yang bisa berdiri dengan dua kaki belakang dan berkantong?", a: "kanguru" },
  { q: "Hewan yang berbulu tebal dan tinggal di pegunungan es?", a: "yak" },
  { q: "Hewan pemalas yang tinggal di pohon dan sangat lambat?", a: "sloth" },
  { q: "Hewan yang suaranya 'mooo'?", a: "sapi" },
  { q: "Hewan yang punya paruh lebar dan suka air?", a: "bebek" },
  { q: "Hewan kecil yang bisa terbang dan menyengat?", a: "lebah" },
  { q: "Hewan yang punya ekor panjang dan pintar memanjat?", a: "monyet" },
  { q: "Hewan laut yang tubuhnya seperti payung dan bisa menyengat?", a: "ubur-ubur" },
  { q: "Hewan laut dengan sisik berkilau dan insang?", a: "ikan" },
  { q: "Hewan kecil yang hidup di rumah dan suka ke gula?", a: "semut" },
  { q: "Hewan bersisik yang hidup di gurun dan merayap?", a: "kadal" },
  { q: "Hewan lucu dari kutub selatan dan suka seluncur di es?", a: "penguin" },
  { q: "Hewan dengan tanduk spiral yang tinggal di gunung?", a: "kambing gunung" }
];
